language: node_js
node_js:
  - 10
  - 12
dist: trusty
env:
  - PORT=5000
cache:
  directories:
    - "node_modules"
install:
  - npm install
  - npm run build
script:
  - nohup npm run start &
  - sleep 3
  - npm run test
